POST http://localhost:2009/api/v4/login
Content-Type: application/json

{
  "email": "chen-gz@outlook.com",
  "password": "Connie"
}

###
POST localhost:2009/api/v4/get_post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNoZW4tZ3pAb3V0bG9vay5jb20iLCJleHAiOjE2OTY5OTgzNjQsImlhdCI6MTY5NjM5MzU2NH0.QF0bD-WZBwRGNYTnUYxTf-evPAGa1c3L3zJwcL1iDIo

{
  "url": "100",
  "rendered": false
}

###
POST localhost:2009/api/v4/search_posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNoZW4tZ3pAb3V0bG9vay5jb20iLCJleHAiOjE2OTY5OTgzNjQsImlhdCI6MTY5NjM5MzU2NH0.QF0bD-WZBwRGNYTnUYxTf-evPAGa1c3L3zJwcL1iDIo

{
  "author": "Guangzong",
  "title": "",
  "limit": {
    "start": 0,
    "size": 10
  }
}

###
POST localhost:2009/api/v4/get_distinct
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNoZW4tZ3pAb3V0bG9vay5jb20iLCJleHAiOjE2OTY5OTgzNjQsImlhdCI6MTY5NjM5MzU2NH0.QF0bD-WZBwRGNYTnUYxTf-evPAGa1c3L3zJwcL1iDIo

{
  "field": "url"
}

###
POST localhost:2009/api/v4/update_post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNoZW4tZ3pAb3V0bG9vay5jb20iLCJleHAiOjE2OTY5OTgzNjQsImlhdCI6MTY5NjM5MzU2NH0.QF0bD-WZBwRGNYTnUYxTf-evPAGa1c3L3zJwcL1iDIo

{
  "id": 1,
  "url": "hello",
  "title": "4 Continuity",
  "content": "test",
  "author": "Guangzong",
  "rendered": false
}

###
POST localhost:2009/api/blog_file/v1/get_presigned_url
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNoZW4tZ3pAb3V0bG9vay5jb20iLCJleHAiOjE2OTY5OTgzNjQsImlhdCI6MTY5NjM5MzU2NH0.QF0bD-WZBwRGNYTnUYxTf-evPAGa1c3L3zJwcL1iDIo

{
  "file_name": "test.txt",
  "hash_crc32": "12345678"
}

###
PUT https://minio.ggeta.com/blog-public-data/test.txt_12345678?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=HI4mSQabJ6GWesqES4V4%2F20231005%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20231005T010939Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=d3357b36d8877db3c27e4bb3c0a46e33d2c608ed3271b772df94af31443dd64b"
Content-Type: application/octet-stream


###
POST localhost:2009/api/photo/v1/insert_photo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNoZW4tZ3pAb3V0bG9vay5jb20iLCJleHAiOjE2OTc0MjU2ODgsImlhdCI6MTY5NjgyMDg4OH0.fDW-p3nkPXuHjozwxK728Dxff5Yk-RSzwvSVIhfuTvg

{
  "hash": "hello_world2",
  "has_original": true,
  "original_ext": "hello"
}

###
POST localhost:2009/api/photo/v1/get_photo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNoZW4tZ3pAb3V0bG9vay5jb20iLCJleHAiOjE2OTc0MjU2ODgsImlhdCI6MTY5NjgyMDg4OH0.fDW-p3nkPXuHjozwxK728Dxff5Yk-RSzwvSVIhfuTvg

{
  "id" : 6
}

###
GET localhost:2009/api/photo/v1/get_photo_list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNoZW4tZ3pAb3V0bG9vay5jb20iLCJleHAiOjE2OTc0MjU2ODgsImlhdCI6MTY5NjgyMDg4OH0.fDW-p3nkPXuHjozwxK728Dxff5Yk-RSzwvSVIhfuTvg

###
GET localhost:2009/api/photo/v2/get_photo_id/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ.eyJlbWFpbCI6ImNoZW4tZ3pAb3V0bG9vay5jb20iLCJleHAiOjE2OTc0MjU2ODgsImlhdCI6MTY5NjgyMDg4OH0.fDW-p3nkPXuHjozwxK728Dxff5Yk-RSzwvSVIhfuTvg


###
GET localhost:2009/api/photo/v2/get_photo_hash/f578aab03da9f32fa30c7f2e33ea4ecf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNoZW4tZ3pAb3V0bG9vay5jb20iLCJleHAiOjE2OTc0MjU2ODgsImlhdCI6MTY5NjgyMDg4OH0.fDW-p3nkPXuHjozwxK728Dxff5Yk-RSzwvSVIhfuTvg
